Improve test cases
Morriar/Missions pull request #127
Opened 2016-09-19 20:11 UTC by privat

this cleanup a little the `submission` classes and related info and fix some related bugs

2016-09-19 20:12 UTC, Morriar commented on src/model/missions.nit
> +	var number: Int
I like this, the UI likes this, everybody like this.

2016-09-19 20:13 UTC, Morriar commented on src/model/engines/engine_base.nit
> +			submission.results.clear
I see factorizable code here.

2016-09-19 20:14 UTC, Morriar commented on src/model/engines/engine_base.nit
> +		if submission.mission.testsuite.is_empty then
Good one

2016-09-19 20:18 UTC, Morriar commented on www/directives/missions/submit.html
> -		<div class='card' ng-if='result.compilation_failed'>
In the same file, you should also replace `index` by `testRes.testcase.number`.

2016-09-19 20:20 UTC, Morriar reviewed
Mostly a +1, I would love to see a reroll with some factorization about submissions errors (same code used at least 3 times) and changes in the `submit.html` frontend to use the test case numbering.

2016-09-20 00:03 UTC, privat commented on www/directives/missions/submit.html
> -		<div class='card' ng-if='result.compilation_failed'>
Can do

2016-09-20 00:03 UTC, privat commented on src/model/engines/engine_base.nit
> +			submission.results.clear
Can do

2016-09-20 00:25 UTC, privat commented
update: apply @Morriar's suggestions

2016-09-20 01:15 UTC, Morriar commented on src/model/engines/engine_base.nit
>  			submission.compilation.message = "There is no tests for the mission yet.\nPlease try again later."
Oups, didn't see that one one the first review:

> There is no test~~s~~

And while we are at it, may I suggest:

> There is no test for **this** mission yet.

2016-09-20 01:18 UTC, Morriar commented on src/model/engines/engine_base.nit
> +	do
You see me in the obligation to refer to the [Holly Rules of the Repository, chapter 3, section 1, alinea 2](https://github.com/Morriar/Missions/blob/master/README.md#code-style).

I cite:

> **The do is on the same line as the function declaration.**

Please, just stop this non-sense... The war is over, you just don't want to admit it.

2016-09-20 01:19 UTC, Morriar requested changes

2016-09-20 01:19 UTC, Morriar commented
I'm starting to like this whole `review` thing.

2016-09-20 02:14 UTC, privat commented
apply more suggestions, again and again...

2016-09-21 13:02 UTC, Morriar approved these changes

2016-09-21 13:04 UTC, merged