Migrate to state views
Morriar/Missions pull request #138
Opened 2016-10-11 23:19 UTC by ppepos

Please test-run this as it was difficult to try and test every little feature as all of the pathing and controller resolution was changed.

Thanks <3

Signed-off-by: Philippe Pepos Petitclerc <ppeposp@gmail.com>

2016-10-12 16:14 UTC, Morriar commented
Nothing is displaying on missions-dev.nitlanguage.org.

Reason: 

~~~
Failed to instantiate module ngRoute due to:
Error: [$injector:nomod] http://errors.angularjs.org/1.5.5/$injector/nomod?p0=ngRoute
~~~

Maybe try a `git grep ngRoute` to remove them all.

2016-10-12 16:49 UTC, Morriar requested changes

2016-10-12 16:49 UTC, Morriar commented on www/directives/player/player.html
> +	<panel-404 ng-if='vm.error' />
I'm not against the `vm` controller name but in my experience, having all your controllers named `vm` makes a huge deal with nested controllers.

2016-10-12 16:49 UTC, Morriar commented on www/javascripts/players.js
>  		.controller('PlayerAuth', ['$routeParams', '$rootScope', '$scope', function($routeParams, $rootScope, $scope) {
I see a `routeParams` here

2016-10-13 12:38 UTC, privat commented
I close the PR so that http://missions-dev.nitlanguage.org can be functionnal again, reopen it when the `routeParams` are OK.

2016-10-13 12:38 UTC, closed without merging

2016-10-13 15:49 UTC, ppepos commented
Wow can't reopen because `-f`..................

Opening a new one. =/