[add] help command-line options
Morriar/Missions pull request #157
Opened 2016-10-26 22:15 UTC by ventilooo

fix #146 
Signed-off-by: iszalai <szalai972@gmail.com>

2016-10-26 22:27 UTC, privat requested changes
-1 This does not use the existing -h option from popcorn nor the facilities of the opts library.

2016-10-27 01:23 UTC, ppepos commented
What @privat said.

2016-10-27 17:48 UTC, ventilooo commented
reroll

2016-10-27 17:54 UTC, lbajolet requested changes
When both my remarks are addressed, I'd say +1 unless someone else votes against

2016-10-27 17:54 UTC, R4PaSs commented on src/app.nit
> +if opts.opt_help.value == true then
No need for the `== true` as value is already a boolean

2016-10-27 17:54 UTC, R4PaSs commented on src/app.nit
> +    exit(0)
From what I remember, @privat advises against `exit(0)` in favor of a `return 0`

2016-10-27 18:33 UTC, ventilooo commented
fix according to @R4PaSs review

2016-10-27 23:54 UTC, privat approved these changes

2016-10-27 23:55 UTC, privat commented
ok to test

2016-10-31 18:04 UTC, lbajolet approved these changes

2016-11-03 22:45 UTC, merged